/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testcreatefiles;

import java.io.IOException;
import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oem
 */

public class uiFormulario extends javax.swing.JFrame {

    ArrayList<Alumns> alumnsCollection = new ArrayList<Alumns>();
    private int x = 0;

    /**
     * Creates new form uiFormulario
     */
    public uiFormulario() throws IOException {
        initComponents();
        createElementCheckbox();
        initTableAlumns();
    }

    public void initTableAlumns() throws IOException {
        this.alumnsCollection = ControllerFIles.getCollectionAlumns();
        Object[][] Alumns = new Object[this.alumnsCollection.size()][4];
        String[] headerColumns = new String[4];
        headerColumns[0] = "Nombre";
        headerColumns[1] = "Correo Electronico";
        headerColumns[2] = "Carrera";
        headerColumns[3] = "Semestre";
        this.x = 0;
        this.alumnsCollection.stream().forEach(alumn -> {
            Alumns[x][0] = alumn.getName();
            Alumns[x][1] = alumn.getEmail();
            Alumns[x][3] = alumn.getCarrera();
            Alumns[x][2] = alumn.getLevel();
            this.x += 1;
        });

        DefaultTableModel modelTable = new DefaultTableModel(Alumns, headerColumns);
        jTableAlumns.setModel(modelTable);
    }

    private void createElementCheckbox() {
        checkboxCarrera.removeAllItems();
        checkboxLevel.removeAllItems();

        checkboxCarrera.addItem("Ing. Informartica");
        checkboxCarrera.addItem("Ing. Tic's");
        checkboxCarrera.addItem("Ing. Agronomia");
        checkboxCarrera.addItem("Ing. Forestal");
        checkboxCarrera.addItem("Lic. Bologia");

        checkboxLevel.addItem("Primer Semestre");
        checkboxLevel.addItem("Segundo Semestre");
        checkboxLevel.addItem("Tercer Semestre");
        checkboxLevel.addItem("Cuarto Semestre");
        checkboxLevel.addItem("Septimo Semestre");
        checkboxLevel.addItem("Octavo Semestre");
        checkboxLevel.addItem("Noveno Semestre");
        checkboxLevel.addItem("Decimo Semestre");
        checkboxLevel.addItem("Onceavo Semestre");
        checkboxLevel.addItem("Doceavo Semestre");
    }

    private String valideInforForm(String name, String email, String carrera, String level) {
        String message = "";
        if (name.isEmpty()) {
            message = message + "Nombre, ";
        }
        if (email.isEmpty()) {
            message = message + "Correo electronico";
        }
        if (carrera.isEmpty()) {
            message = message + "Carrera";
        }
        if (carrera.isEmpty()) {
            message = message + "Semestre";
        }
        if (!(message.isEmpty())) {
            return "Se requiere los siguientes datos: " + message;
        }
        return "";
    }

    private void cleanTexfields() {
        inputName.setText("");
        inputEmail.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        checkboxCarrera = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        checkboxLevel = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumns = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(52, 73, 94));

        jLabel1.setText("Cuestionario");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Correo Electronico:");

        jLabel4.setText("Carrera");

        checkboxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Semestre");

        checkboxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Guardar Datos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTableAlumns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAlumns);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputName)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkboxCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(102, 102, 102))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(checkboxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(inputEmail)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(251, 251, 251))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String tempName = inputName.getText();
        String tempEmail = inputEmail.getText();
        String tempLevel = checkboxCarrera.getSelectedItem().toString();
        String tempCarrera = checkboxLevel.getSelectedItem().toString();
        String valide = this.valideInforForm(tempName, tempEmail, tempLevel, tempCarrera);
        if ((valide.isEmpty())) {
            Alumns tempAlumns = new Alumns(tempName, tempEmail, tempLevel, tempCarrera);
            this.alumnsCollection.add(tempAlumns);
            if (ControllerFIles.createFile(alumnsCollection)) {
                this.cleanTexfields();;
                JOptionPane.showMessageDialog(null, "Alumno registrado");
                try {
                    this.initTableAlumns();
                } catch (IOException ex) {
                    Logger.getLogger(uiFormulario.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    ControllerFIles.getCollectionAlumns();
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, valide);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uiFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uiFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uiFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uiFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new uiFormulario().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(uiFormulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> checkboxCarrera;
    private javax.swing.JComboBox<String> checkboxLevel;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlumns;
    // End of variables declaration//GEN-END:variables
}
